# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

QA = "QA"

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build and Deploy QA version on Firebase App Distribution"
  lane :qa do
    # Function:
    #   This lane builds the QA version of the app and deploys it to Firebase App Distribution.

    environment = QA
    version_code = ENV['GITHUB_RUNNER_NUMBER']
    base_api = ENV['BASE_URL']

    version_name, changelog = generate_changelog(
        tag_match: "#{environment}/*",
    )

    build(
        environment: environment,
        version_name: version_name,
        version_code: version_code,
        base_api: base_api
    )

    publish_on_firebase(
        environment: environment,
        changelog: changelog
    )

    pos_deploy(tag: "qa/#{next_version}")
  end

  desc "Create local properties and return it"
  private_lane :create_local_properties do |options|
    # Parameters:
    #   :version_name (String): The version name of the app.
    #   :version_code (String): The version code of the app.
    #   :base_api (String): The base API URL.
    # Function:
    #   This lane creates the local properties based on the provided options.

    version_name = options[:version_name]
    version_code = options[:version_code]
    base_api = options[:base_api]

    local_properties = {
        'BASE_URL' => base_api,
        'CI_VERSION_NAME' => version_name,
        'CI_VERSION_CODE' => version_code,
    }
  end

  desc "Build android project"
  private_lane :build do |options|
    # Parameters:
    #   :environment (String): The build environment (e.g., QA).
    #   :version_name (String): The version name of the app.
    #   :version_code (String): The version code of the app.
    #   :base_api (String): The base API URL.
    # Function:
    #   This lane builds the Android project using the provided options.

    environment = options[:environment]
    version_name = options[:version_name]
    version_code = options[:version_code]
    base_api = options[:base_api]

    local_properties = create_local_properties(
        version_name: version_name,
        version_code: version_code,
        base_api: base_api
    )

    case environment
    when QA
        gradle_task = 'clean assemble'
        gradle_build_type = 'Debug'
    end

    gradle(
        task: gradle_task,
        build_type: gradle_build_type,
        print_command: false,
        properties: local_properties
    )
  end

  desc "Publish version on Firebase App Distribution"
  private_lane :publish_on_firebase do |options|
    # Parameters:
    #   :environment (String): The build environment (e.g., QA).
    #   :changelog (String): The changelog for this release.
    # Function:
    #   This lane publishes the built app version on Firebase App Distribution using the provided options.

    environment = options[:environment]
    changelog = options[:changelog]

    case environment
    when QA
        groups = "routinely---qa"
    end

    firebase_app_distribution(
        app: ENV['FIREBASE_APP_ID'],
        groups: groups,
        release_notes: changelog,
        service_credentials_file: "credential_file_content.json"
    )
  end

  desc "Generate tag and changelog by semantic versioning 2.0.0"
  private_lane :generate_changelog do |options|
    # Parameters:
    #   :tag_match (String): The pattern to match tags.
    # Output:
    #   [String, String]: The next version and the changelog.
    # Function:
    #   This lane generates the next version and changelog based on semantic versioning.

    match = options[:tag_match]
    git_pull(only_tags: true)

    analyze_commits(
        match: match,
    )

    next_version = lane_context[SharedValues::RELEASE_NEXT_VERSION]

    changelog = conventional_changelog(
        format: 'slack',
        title: 'Android Alpha',
        display_author: false,
        display_links: false,
        debug: false
    )

    return next_version, changelog
  end

  desc "Lane to be executed after each deploy lane"
  private_lane :pos_deploy do |options|
    # Parameters:
    #   :tag (String): The tag to be created.
    #   :changelog (String): The changelog for the tag.
    # Function:
    #   This lane is executed after each deploy lane, creating and pushing a git tag.

    tag = options[:tag]
    changelog = options[:changelog]

    add_git_tag(tag: tag, message: changelog)
    push_git_tags
  end
end

desc "Create and push a git tag"
lane :create_and_push_tag do |options|
  # Parameters:
  #   :tag (String): The tag to be created.
  # Function:
  #   This lane creates a git tag and pushes it to the remote repository.

  tag = options[:tag]

  if tag.nil? || tag.empty?
    UI.user_error!("You must provide a tag name.")
  end

  sh("git tag #{tag}")
  sh("git push origin #{tag}")
end
