name: Deploy QA

# on:
#   push:
#     branches:
#       - homolog
on:
  pull_request:
    branches:
      - "*"

jobs:
  build_and_deploy:
    name: Build
    runs-on: ubuntu-22.04
    env:
      isCI: "true"
      BASE_SCHEME: ${{ secrets.BASE_URL_DEBUG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: "17"

      - name: Bump version and push tag
        id: tag_semantic
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: develop
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Testing tag_semantic
        shell: bash
        env:
          TAG_VERSION: ${{steps.tag_semantic.outputs.tag}}
        run: |
          echo "Tag Semantic"
          echo "${TAG_VERSION}"
      # - name: Create local.properties
      #   run: echo "BASE_URL=${BASE_SCHEME}" >> local.properties

      # - name: Build android
      #   run: ./gradlew assembleDebug --stacktrace
